[package]
name = "lab"
version = "0.4.3" # bump html_root_url attribute in lib.rs
authors = ["Jesse Bees <jesse@toomanybees.com>"]
description = """
Tools for converting RGB colors to the CIE-L*a*b* color space, and
comparing differences in color.
"""
homepage = "https://github.com/TooManyBees/lab"
repository = "https://github.com/TooManyBees/lab"
documentation = "https://docs.rs/lab"
readme = "README.md"
keywords = ["lab", "color", "pixel", "rgb"]
categories = ["multimedia::images", "multimedia::video"]
license = "MIT"

[lib]
bench = false

[dev-dependencies]
rand = "0.5"
criterion = "0.2"
lazy_static = "*"
pretty_assertions = "0.5"

[[bench]]
name = "rgb_to_lab"
harness = false
